#!/usr/bin/env bash

awesome_dir="~/awesome"
bin_dir="~/bin"

fn_checkDir() {
    if [[ -z $1 ]]; then
        echo "Specify the directory."
        exit 1
    fi
    if [[ ! -d $1 ]]; then
        mkdir $1
    fi
}

fn_install() {
    cd ${awesome_dir}

    echo "from install script."
    exit
}

fn_checkDir $awesome_dir
fn_checkDir $bin_dir
fn_install
