#!/usr/bin/env bash

install() {
    echo "installing ..."
}

uninstall() {
    echo "uninstalling ..."
}

echo "test 2"

fn_main() {
    if [ $# -eq 1 ]; then
        case $1 in
        "minstall")
            install
            ;;
        "muninstall")
            uninstall
            ;;
        esac
    else
        echo "M... something wrong."
        exit 1
    fi
}

fn_main "$@"
