#!/usr/bin/env bash

readme() {
    echo "starting ..."
    read -rp "Do you want to continue? yes/y or no/n   " PANS
    ans=$(echo "$PANS" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
    if [[ "$ans" = "Y" ]]; then
        echo "confirmed 1."
    fi
    echo "done"
}

install() {
    echo "installing ..."
    readme
    echo "done"
}

uninstall() {
    echo "uninstalling ..."
}

echo "test 2"

fn_main() {
    if [ $# -eq 1 ]; then
        case $1 in
        "minstall")
            install
            ;;
        "muninstall")
            uninstall
            ;;
        esac
    else
        echo "M... something wrong."
        exit 1
    fi
}

fn_main "$@"
