#!/usr/bin/env bash

fn_test1() {
    echo "starting ..."
    read -rp "Do you want to continue? yes/y or no/n   " PANS
    ans=$(echo "$PANS" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
    if [[ "$ans" = "Y" ]]; then
        echo "confirmed 1."
    fi
    echo "done"
}

fn_main() {
    if [ $# -eq 1 ]; then
        case $1 in
        "test")
            fn_test1
            ;;
        esac
    else
        echo "Something wrong."
        exit 1
    fi
}

fn_main "$@"