#!/usr/bin/env bash

# fn_confirm() {
#     local dir="$1"
#     read -rp "Do you want to ${dir}? yes/y or no/n   " PANS
#     ans=$(echo "$PANS" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
#     echo "$ans"
# }

fn_test1() {
    echo "checking.."
    read -rp "Do you want to ${dir}? yes/y or no/n   " PANS
    ans=$(echo "$PANS" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
    if [[ "$ans" = "Y" ]]; then
        echo "confirmed 1."
    fi
    echo "done"
    # fn_confirm remove
    # confirm_symlink=$(fn_confirm remove)
    # echo "$confirm_symlink"
    # if [[ "$confirm_symlink" = "Y" ]]; then

    #     echo "Removed the symlink."

    # fi
}

fn_main() {
    if [ $# -eq 1 ]; then
        case $1 in
        "test")
            fn_test1
            ;;
        esac
    else
        echo "Something wrong."
        exit 1
    fi
}

fn_main "$@"
