#!/usr/bin/env bash

bin_dir="$HOME/bin"

fn_find_symlinks() {
    paths=$(find "$bin_dir" -type l)
    echo "$paths"
}

fn_test1() {
    mapfile -t links < <(fn_find_symlinks)
    echo "Number of symlinks: ${#links[@]}"
    if [ "${#links[@]}" -gt 0 ]; then
        echo "${#links[@]} is greater than 1."
    else
        echo " ${#links[@]} is not greater than 0."
    fi
}

fn_main() {
    if [ $# -eq 1 ]; then
        case $1 in
        "test")
            fn_test1
            ;;
        esac
    else
        echo "Something wrong."
        exit 1
    fi
}

fn_main "$@"
